# Wolfxygen
# by Wolfyxon

# If you're using multiworld you will have to add each nether world name.
# Worlds are by default located in the server root directory.

affectedWorlds: # Players will have to breath only in these worlds/dimensions
  - "world_nether"
  - "world_the_end"
affectedGamemodes: # Players will have to breath only if they have one of these gamemodes.
  - "survival"
  - "adventure"

refillInUnaffectedGamemodes: true
refillInUnaffectedWorlds: true

waterBreathingPotion:
  loseOxygen: false # Lose oxygen when has water breathing effect
  refill: true # Refill oxygen when has water breathing effect

numbers:
  maxOxygen: 500
  subtractionAmount: 1
  refillingAmount: 1.5
  intervalTicks: 20 # Plugin will check, subtract oxygen and damage players every X ticks. 20 ticks == 1 second
  damage: 0.5 # Damage dealt when player has no oxygen


# To disable a message, set it to: ""
messages:
  fullyRefilledOtherPlayer: "Refilled {playername}'s oxygen."
  fullyRefilled: "Your oxygen has been refilled."
  noPermission: "&cYou are not allowed to do that!"

potions:
  name: "&lOxygen bottle"
  color: "white"
  lore: "&a+{oxygen}" # bottom text shown when hovering on the potion. {oxygen} will be replaced by the restored oxygen
  defaultOxygen: 20 # default amount of how much oxygen the potion restores

display:
  #TODO: actionBar
  mode: "bossBar" # available options: bossBar
  showWhenFull: false

  bossBar:
    title: "Oxygen"
    color: "white"

  actionBarPercentageStyles:
    #IMPORTANT: the numbers are in percentages, not oxygen values.
    #{oxygen} will be replaced by the player's oxygen amount.
    80: "&b☁️{oxygen}"
    40: "&6☁️{oxygen}"
    30: "&c☁️{oxygen}"
    10: "&4☁️{oxygen}"